name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-python@v4
        - name: Run tests
          run: |
            git clone 'https://mpr.makedeb.org/just' && cd just && makedeb -si
            cd 2023/python
            just test
